timezone: Asia/Tokyo
source: .
plugins_dir: ./_plugins
layouts_dir: ./_layouts
destination: ./_site
encoding: utf-8
safe: false
port: 4000
baseurl: /
permalink: date
name: de-liKeR
description: CreatorQsF Blog
url: https://de-liker.com
